server:
  port: 3000
  host: 0.0.0.0

redis:
  url: redis://redis-cache:6379 # O 'redis://localhost:6379' si corres el proceso nativo en tu máquina
  onFailure: open

logging:
  level: info

routes:
  # ===============================================================
  # Ruta Pública (Redirige al Backend Mock)
  # ===============================================================
  - prefix: /public
    target: http://mock-service:8080
    stripPrefix: true

  # ===============================================================
  # Ruta Protegida con JWT (Redirige al Backend Mock)
  # ===============================================================
  - prefix: /secure
    target: http://mock-service:8080
    stripPrefix: true
    jwt:
      enabled: true
      secret: "secreto-para-pruebas-locales-de-32-chars!!!"
      algorithm: HS256
      forwardClaims:
        - sub
        - role
        - email

  # ===============================================================
  # Ruta mapeada a la PokéAPI Real
  # ===============================================================
  - prefix: /api
    target: https://pokeapi.co/api/v2
    stripPrefix: true
    rateLimit:
      maxRequests: 8
      windowSeconds: 60

  # ===============================================================
  # Ruta de Pruebas Públicas con httpbin.org (Protegida con JWT)
  # ===============================================================
  - prefix: /httpbin
    target: https://httpbin.org
    stripPrefix: true
    jwt:
      enabled: true
      secret: "secreto-para-pruebas-locales-de-32-chars!!!"
      algorithm: HS256
      forwardClaims:
        - sub
        - role
        - email
